//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fitness
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string f_Percentage { get; set; }
        [Required]
        public string InjuryStatus { get; set; }
        [Required]
        public int OverallRating { get; set; }
    }
}
