//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public Nullable<int> Id { get; set; }
        public string Opponent { get; set; }
        public string Match_Status { get; set; }
        public System.DateTime Match_Date { get; set; }
        public string Result { get; set; }
    }
}
