//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public string SalaryGrade { get; set; }
        public Nullable<int> Bonus { get; set; }
        public string SalaryStatus { get; set; }
    }
}
