//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Performance()
        {
            this.tbl_Profile = new HashSet<tbl_Profile>();
        }
    
        public int RankId { get; set; }

        [Required]
        public string RankName { get; set; }
        [Required]
        public int Goals { get; set; }
        [Required]
        public int RedCards { get; set; }
        [Required]
        public int YellowCards { get; set; }
        [Required]
        public int Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Profile> tbl_Profile { get; set; }
    }
}
