//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string E_Designation { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime ContactYear { get; set; }
    }
}
